### ISSUE TITLE
The installer need to be modified to include these

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/clr-bundles#13] opened 2017-09-23 05:52 UTC
1) Should provide a way to connect to the wireless(wi-fi) network.

2) Should display what it is doing on the terminal, while fetching bundle and installing.

**Comment by bryteise** [comment] 2017-09-23 07:59
@matthewrsj An fyi for feature requests.

**Comment by matthewrsj** [comment] 2017-09-25 16:46
> Should provide a way to connect to the wireless(wi-fi) network.

I'll open an issue on the installer

> Should display what it is doing on the terminal, while fetching bundle and installing.

It does display what is happening on the terminal. It directly reports the output from swupd. This output is sub-par. A bug is already open here: https://github.com/clearlinux/swupd-client/issues/256

**Comment by bryteise** [comment] 2017-09-25 17:08
Closing this as the issue is open on the installer now.

**Closed by bryteise** 2017-09-25 17:08 UTC
